### ISSUE TITLE
When to publish the tensorflow code？

### ISSUE THREAD

**Issue by zjh-nudger** [yangliuy/aNMM-CIKM16#1]
When to publish the tensorflow code？Thanks very much.

**Comment by yangliuy** [comment]
I am still developing and updating the tensorflow version. I will release it when I have a stable version.

Thanks!

**Comment by jstol** [comment]
@yangliuy I'd also be very interested in seeing the TF code for this. Any progress so far?

**Comment by yangliuy** [comment]
I will release the code later. The tricky part is that you need to pre-compute a question-answer sentence match matrix before feeding the data into TF computing graph. You can also try to implement it by yourself.

**Comment by yangliuy** [comment]
@zjh-nudger @jstol 
I can answer your question now :) The answer is the code in MatchZoo.
The implementation of aNMM using Python/Tensorflow/Keras has been released in the MatchZoo toolkit (https://github.com/faneshion/MatchZoo). You can take a look at this deep text matching toolkit to see the implementations of popular deep text matching models such as ARC-I/ARC-II, DSSM, CDSSM, MatchPyramid, MV-LSTM, DRMM, aNMM, Duet, etc. We will add more deep text matching models into it. Stay tuned.
